name: "Test and deploy"

on :
  pull_request:
    branches: ["master" , "dev" , "main"]
  
  push:
    branches : ["master" , "dev" , "main"]

jobs:
  main:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up the node js enviroment
        uses: actions/setup-node@v6
        with:
           node-version: '20'

      - name: Install dependicies
        run: npm i

      - name: Apply the migration
        run:  cd ./src && npx prisma migrate deploy

      - name: Generate the Prisma Client
        run: cd ./src && npx prisma generate 

      - name: Build the project
        run: npm run build

      # - name:  Run Test and lint 
      #   run: npm test

      - name:  Build a docker file
        run:  docker build -t anshshr/metaverse .

      - name: Push to the docker hub
        run:  docker  push anshshr/metaverse:latest